#!/usr/bin/env python3
"""PPTX semantic Content Lock snapshot and verifier.

Traditional Chinese / English:
- Protect presentation content, data, media and behavior semantics.
- Ignore allowed visual formatting, geometry and content-free native decorative shapes.
- Fail closed when protected semantics differ.

Content-free decorative AutoShapes are visual scaffolding, not presentation
content. Empty paragraphs generated by those shapes are therefore ignored;
visible text, list semantics, hyperlinks, media and all other protected
semantics remain locked.
"""

from __future__ import annotations
import argparse, hashlib, json, posixpath, sys, zipfile
from pathlib import PurePosixPath
import xml.etree.ElementTree as ET
NS = {'a': 'http://schemas.openxmlformats.org/drawingml/2006/main', 'p': 'http://schemas.openxmlformats.org/presentationml/2006/main', 'r': 'http://schemas.openxmlformats.org/officeDocument/2006/relationships', 'c': 'http://schemas.openxmlformats.org/drawingml/2006/chart', 'm': 'http://schemas.openxmlformats.org/officeDocument/2006/math'}
R_NS_PREFIX = '{%s}' % NS['r']
R_ID = R_NS_PREFIX + 'id'
R_EMBED = R_NS_PREFIX + 'embed'
R_LINK = R_NS_PREFIX + 'link'
TABLE_SEMANTIC_ATTRS = {'gridSpan', 'rowSpan', 'hMerge', 'vMerge'}
VISUAL_RELATION_TYPE_FRAGMENTS = {'diagramLayout', 'diagramQuickStyle', 'diagramColors', 'theme'}

def sha256(data):
    return hashlib.sha256(data).hexdigest()

def stable_key(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(',', ':'))

def local_name(name):
    return name.rsplit('}', 1)[1] if '}' in name else name

def read_xml(zf, path):
    try:
        return ET.fromstring(zf.read(path))
    except KeyError:
        return None

def rels_path(part_path):
    p = PurePosixPath(part_path)
    return str(p.parent / '_rels' / (p.name + '.rels'))

def resolve_target(source_part, target):
    return target.lstrip('/') if target.startswith('/') else posixpath.normpath(posixpath.join(posixpath.dirname(source_part), target))

def relationships(zf, source_part):
    root = read_xml(zf, rels_path(source_part))
    out = {}
    if root is None:
        return out
    for rel in list(root):
        rid = rel.attrib.get('Id')
        target = rel.attrib.get('Target', '')
        mode = rel.attrib.get('TargetMode')
        typ = rel.attrib.get('Type', '')
        if rid:
            out[rid] = {'target': target if mode == 'External' else resolve_target(source_part, target), 'external': mode == 'External', 'type': typ}
    return out

def canonical_element(node):
    if node is None:
        return None
    attrs = {local_name(k): v for k, v in sorted(node.attrib.items(), key=lambda kv: local_name(kv[0]))}
    return {'tag': local_name(node.tag), 'attrs': attrs, 'text': node.text or '', 'children': [canonical_element(c) for c in list(node)]}

def paragraph_semantics(root):
    if root is None:
        return []
    out = []
    for p in root.findall('.//a:p', NS):
        text = ''.join((n.text or '' for n in p.findall('.//a:t', NS)))
        ppr = p.find('./a:pPr', NS)
        level = ppr.attrib.get('lvl') if ppr is not None else None
        bullet = None
        if ppr is not None:
            for child in list(ppr):
                kind = local_name(child.tag)
                if kind == 'buChar':
                    bullet = {'kind': kind, 'char': child.attrib.get('char', '')}
                    break
                if kind == 'buAutoNum':
                    bullet = {'kind': kind, 'type': child.attrib.get('type', ''), 'startAt': child.attrib.get('startAt')}
                    break
                if kind in {'buNone', 'buBlip'}:
                    bullet = {'kind': kind}
                    break
        if text or level is not None or bullet is not None:
            out.append({'text': text, 'level': level, 'bullet': bullet})
    return out

def extract_math(root):
    return [] if root is None else [canonical_element(n) for n in root.findall('.//m:oMath', NS)]

def extract_tables(root):
    tables = []
    if root is None:
        return tables
    for tbl in root.findall('.//a:tbl', NS):
        rows = []
        for tr in tbl.findall('./a:tr', NS):
            cells = []
            for tc in tr.findall('./a:tc', NS):
                semantic_attrs = {local_name(k): v for k, v in sorted(tc.attrib.items()) if local_name(k) in TABLE_SEMANTIC_ATTRS}
                cells.append({'paragraphs': paragraph_semantics(tc), 'merge': semantic_attrs})
            rows.append(cells)
        tables.append(rows)
    return tables

def chart_semantics(root):
    if root is None:
        return {}
    formulas = [x.text or '' for x in root.findall('.//c:f', NS)]
    values = [x.text or '' for x in root.findall('.//c:v', NS)]
    series = [x.text or '' for x in root.findall('.//c:tx//c:v', NS)]
    pts = []
    for n in root.findall('.//c:pt', NS):
        v = n.find('./c:v', NS)
        pts.append({'idx': n.attrib.get('idx'), 'v': '' if v is None or v.text is None else v.text})
    return {'paragraphs': paragraph_semantics(root), 'formulas': formulas, 'values': values, 'series_text': series, 'points': pts}

def slide_order(zf):
    pres = read_xml(zf, 'ppt/presentation.xml')
    rels = relationships(zf, 'ppt/presentation.xml')
    out = []
    if pres is None:
        return out
    for sid in pres.findall('.//p:sldId', NS):
        rid = sid.attrib.get(R_ID)
        rel = rels.get(rid or '')
        if rel and (not rel['external']):
            out.append(rel['target'])
    return out

def crop_states(zf, root, rels):
    out = []
    if root is None:
        return out
    for bf in root.findall('.//p:blipFill', NS):
        blip = bf.find('./a:blip', NS)
        src = bf.find('./a:srcRect', NS)
        rid = blip.attrib.get(R_EMBED) or blip.attrib.get(R_LINK) if blip is not None else None
        image_hash = None
        external_target = None
        rel = rels.get(rid or '')
        if rel:
            if rel['external']:
                external_target = rel['target']
            else:
                try:
                    image_hash = sha256(zf.read(rel['target']))
                except KeyError:
                    image_hash = 'MISSING'
        out.append({'image_sha256': image_hash, 'external_target': external_target, 'srcRect': dict(sorted(src.attrib.items())) if src is not None else {}})
    return sorted(out, key=stable_key)

def accessibility_semantics(root):
    if root is None:
        return []
    out = []
    for n in root.iter():
        if local_name(n.tag) != 'cNvPr':
            continue
        title = n.attrib.get('title')
        descr = n.attrib.get('descr')
        if title is not None or descr is not None:
            out.append({'title': title or '', 'descr': descr or ''})
    return sorted(out, key=stable_key)

def external_relationship_semantics(rels):
    return sorted([{'target': r['target'], 'type': r['type']} for r in rels.values() if r['external']], key=stable_key)

def _relationship_payload(zf, rel):
    typ = rel['type']
    if any((f in typ for f in VISUAL_RELATION_TYPE_FRAGMENTS)):
        return None
    if rel['external']:
        return {'type': typ, 'external': True, 'target': rel['target']}
    target = rel['target']
    if target.startswith('ppt/media/'):
        try:
            return {'type': typ, 'media_sha256': sha256(zf.read(target))}
        except KeyError:
            return {'type': typ, 'media_sha256': 'MISSING'}
    if target.startswith('ppt/charts/'):
        return {'type': typ, 'chart': chart_semantics(read_xml(zf, target))}
    if target.startswith('ppt/embeddings/') or 'oleObject' in typ or 'package' in typ:
        try:
            return {'type': typ, 'payload_sha256': sha256(zf.read(target))}
        except KeyError:
            return {'type': typ, 'payload_sha256': 'MISSING'}
    if 'diagramData' in typ or target.startswith('ppt/diagrams/data'):
        dr = read_xml(zf, target)
        return {'type': typ, 'diagram_paragraphs': paragraph_semantics(dr), 'diagram_math': extract_math(dr)}
    return {'type': typ, 'target': target}

def relationship_uses(zf, root, rels):
    if root is None:
        return []
    out = []
    for node in root.iter():
        for attr_name, rid in node.attrib.items():
            if not attr_name.startswith(R_NS_PREFIX):
                continue
            rel = rels.get(rid)
            if rel is None:
                out.append({'element': local_name(node.tag), 'attr': local_name(attr_name), 'relationship': 'MISSING'})
                continue
            payload = _relationship_payload(zf, rel)
            if payload is None:
                continue
            out.append({'element': local_name(node.tag), 'attr': local_name(attr_name), 'relationship': payload})
    return sorted(out, key=stable_key)

def object_semantics(zf, root, rels):
    if root is None:
        return []
    sp_tree = root.find('.//p:spTree', NS)
    if sp_tree is None:
        return []
    out = []
    skip = {'nvGrpSpPr', 'grpSpPr', 'extLst'}
    for child in list(sp_tree):
        kind = local_name(child.tag)
        if kind in skip:
            continue
        rec = {'kind': kind, 'paragraphs': paragraph_semantics(child), 'math': extract_math(child), 'tables': extract_tables(child), 'crop_states': crop_states(zf, child, rels), 'accessibility': accessibility_semantics(child), 'relationships': relationship_uses(zf, child, rels)}
        if any((rec[k] for k in rec if k != 'kind')):
            out.append(rec)
    return sorted(out, key=stable_key)

def transition_timing_semantics(root):
    if root is None:
        return {'transition': None, 'timing': None}
    return {'transition': canonical_element(root.find('./p:transition', NS)), 'timing': canonical_element(root.find('./p:timing', NS))}

def notes_semantics(zf, path):
    root = read_xml(zf, path)
    rels = relationships(zf, path)
    return {'objects': object_semantics(zf, root, rels), 'external_relationships': external_relationship_semantics(rels)}

def slide_manifest(zf, path):
    root = read_xml(zf, path)
    rels = relationships(zf, path)
    media = []
    charts = []
    notes = None
    embeddings = []
    for rel in rels.values():
        if rel['external']:
            continue
        target = rel['target']
        typ = rel['type']
        if 'image' in typ or 'audio' in typ or 'video' in typ or target.startswith('ppt/media/'):
            try:
                media.append({'sha256': sha256(zf.read(target))})
            except KeyError:
                media.append({'missing': posixpath.basename(target)})
        elif 'chart' in typ or target.startswith('ppt/charts/'):
            charts.append(chart_semantics(read_xml(zf, target)))
        elif 'notesSlide' in typ or target.startswith('ppt/notesSlides/'):
            notes = notes_semantics(zf, target)
        elif 'oleObject' in typ or 'package' in typ or target.startswith('ppt/embeddings/'):
            try:
                embeddings.append({'sha256': sha256(zf.read(target))})
            except KeyError:
                embeddings.append({'missing': posixpath.basename(target)})
    return {'objects': object_semantics(zf, root, rels), 'media': sorted(media, key=stable_key), 'charts': sorted(charts, key=stable_key), 'notes': notes, 'embeddings': sorted(embeddings, key=stable_key), 'external_relationships': external_relationship_semantics(rels), 'slide_show': None if root is None else root.attrib.get('show', '1'), 'transition_timing': transition_timing_semantics(root)}

def package_hashes(zf, prefix):
    return sorted([{'sha256': sha256(zf.read(n))} for n in sorted(zf.namelist()) if n.startswith(prefix) and (not n.endswith('/'))], key=stable_key)

def annotation_hashes(zf):
    out = []
    for n in sorted(zf.namelist()):
        low = n.lower()
        if n.startswith('ppt/') and (not n.endswith('/')) and ('/comments/' in low or 'commentauthors' in low or '/persons/' in low or ('threadedcomment' in low)):
            out.append({'sha256': sha256(zf.read(n))})
    return sorted(out, key=stable_key)

def special_payload_hashes(zf):
    prefixes = ('customXml/', 'ppt/activeX/', 'ppt/ctrlProps/', 'ppt/tags/', 'ppt/vbaProject')
    out = []
    for n in sorted(zf.namelist()):
        if not n.endswith('/') and n.startswith(prefixes):
            out.append({'part': n, 'sha256': sha256(zf.read(n))})
    return out

def off_slide_semantics(zf):
    prefixes = ('ppt/slideMasters/', 'ppt/slideLayouts/', 'ppt/notesMasters/', 'ppt/handoutMasters/', 'ppt/diagrams/data')
    out = []
    for n in sorted(zf.namelist()):
        if not n.endswith('.xml') or not n.startswith(prefixes):
            continue
        root = read_xml(zf, n)
        rels = relationships(zf, n)
        objects = object_semantics(zf, root, rels)
        paragraphs = [] if objects else paragraph_semantics(root)
        math = [] if objects else extract_math(root)
        accessibility = [] if objects else accessibility_semantics(root)
        rel_uses = [] if objects else relationship_uses(zf, root, rels)
        if objects or paragraphs or math or accessibility or rel_uses:
            out.append({'part': n, 'objects': objects, 'paragraphs': paragraphs, 'math': math, 'accessibility': accessibility, 'relationships': rel_uses, 'external_relationships': external_relationship_semantics(rels)})
    return out

def package_external_relationships(zf):
    out = []
    for n in sorted(zf.namelist()):
        if not n.endswith('.rels'):
            continue
        root = read_xml(zf, n)
        if root is None:
            continue
        for rel in list(root):
            if rel.attrib.get('TargetMode') == 'External':
                out.append({'rels_part': n, 'target': rel.attrib.get('Target', ''), 'type': rel.attrib.get('Type', '')})
    return sorted(out, key=stable_key)

def build_manifest(path):
    with zipfile.ZipFile(path, 'r') as zf:
        order = slide_order(zf)
        slides = [slide_manifest(zf, p) for p in order]
        manifest = {'schema': 4, 'slide_count': len(order), 'slides': slides, 'package_media': package_hashes(zf, 'ppt/media/'), 'package_embeddings': package_hashes(zf, 'ppt/embeddings/'), 'annotations': annotation_hashes(zf), 'special_payloads': special_payload_hashes(zf), 'off_slide_semantics': off_slide_semantics(zf), 'package_external_relationships': package_external_relationships(zf)}
    manifest['semantic_sha256'] = sha256(stable_key(manifest).encode('utf-8'))
    return manifest

def diff(a, b, path='$', diffs=None):
    if diffs is None:
        diffs = []
    if type(a) is not type(b):
        diffs.append(f'{path}: type {type(a).__name__} != {type(b).__name__}')
        return diffs
    if isinstance(a, dict):
        for key in sorted(set(a) | set(b)):
            if key == 'semantic_sha256':
                continue
            if key not in a:
                diffs.append(f'{path}.{key}: added')
            elif key not in b:
                diffs.append(f'{path}.{key}: removed')
            else:
                diff(a[key], b[key], f'{path}.{key}', diffs)
    elif isinstance(a, list):
        if len(a) != len(b):
            diffs.append(f'{path}: length {len(a)} != {len(b)}')
        for i, (x, y) in enumerate(zip(a, b)):
            diff(x, y, f'{path}[{i}]', diffs)
    elif a != b:
        diffs.append(f'{path}: {a!r} != {b!r}')
    return diffs

def main():
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest='cmd', required=True)
    p1 = sub.add_parser('snapshot')
    p1.add_argument('pptx')
    p1.add_argument('--out')
    p2 = sub.add_parser('verify')
    p2.add_argument('source')
    p2.add_argument('output')
    args = parser.parse_args()
    try:
        if args.cmd == 'snapshot':
            m = build_manifest(args.pptx)
            payload = json.dumps(m, ensure_ascii=False, indent=2)
            if args.out:
                open(args.out, 'w', encoding='utf-8').write(payload + '\n')
                print(f'manifest={args.out}')
            else:
                print(payload)
            print(f"semantic_sha256={m['semantic_sha256']}")
            return 0
        a = build_manifest(args.source)
        b = build_manifest(args.output)
        ds = diff(a, b)
        ok = not ds
        print(f"CONTENT_LOCK_PASS={('true' if ok else 'false')}")
        print(f"source_sha256={a['semantic_sha256']}")
        print(f"output_sha256={b['semantic_sha256']}")
        print(f'content_differences={len(ds)}')
        for d in ds[:200]:
            print(d)
        return 0 if ok else 2
    except (zipfile.BadZipFile, ET.ParseError, OSError) as exc:
        print('CONTENT_LOCK_PASS=false')
        print(f'ERROR={exc}', file=sys.stderr)
        return 3
if __name__ == '__main__':
    raise SystemExit(main())
